---
- name: Configure Zabbix
  hosts: controller
  tasks:
        - name: Install python pip
          yum: 
                name: python2-pip.noarch
                state: present
        - name: Install zabbix-api
          pip:
                name: zabbix-api
        - name: Source variables and password
          shell: source /trinity/local/trinity.shadow && echo $ZABBIX_ADMIN_PASSWORD
          register: ZABBIX_ADMIN_PASSWORD
        - name: Create host groups
          local_action:
            module: zabbix_group
            server_url: http://127.0.0.1/zabbix 
            login_user: Admin
            login_password: "{{ ZABBIX_ADMIN_PASSWORD.stdout  }}"
            state: present
            host_groups:
              - Example group1
              - Example group2
