---
- hosts: localhost
  strategy: debug
  tasks:
    - name: Create a test cluster
      luna_cluster:
        path: '/trinity/local/luna/' 
        state: "present"
    - name: Delete a test cluster
      luna_cluster:
        state: absent
    - name: Create a test cluster again
      luna_cluster:
        path: '/trinity/local/luna/' 
        state: "present"
    - name: Change a test cluster again
      luna_cluster:
        frontend_address: 10.141.255.252
        frontend_port: 7051
        server_port: 7052
        torrent_listen_port_max: 7100
        torrent_listen_port_min: 7053
        torrent_pidfile: /run/luna/ltorrent.pid
        tracker_interval: 20
        tracker_maxpeers: 210
        tracker_min_interval: 10
        lweb_num_proc: 10
        lweb_pidfile: /run/luna/lweb.pid
        named_include_file: /etc/named.luna.zones
        named_zone_dir: /var/named
        path: /opt/luna/
        state: "present"
    - name: Cluster makedhcp
      luna_cluster:
        makedhcp: True
        network: cluster
        start_ip: 10.141.0.100
        end_ip: 10.141.0.200
#    - name: Create a test1 bmcsetup
#      luna_bmcsetup:
#        name: "Test1"
#        user: "Test"
#        password: "Test"
#        state: "present"
#    - name: Change a test1 bmcsetup
#      luna_bmcsetup:
#        name: "Test1"
#        userid: 10
#        state: "present"
