---
- hosts: localhost
  tasks:
    - name: Create a test network
      luna_network:
        name: "Test"
        network: "192.16.1.0"
        prefix: 24
        state: "present"
    - name: Delete a test network
      luna_network:
        name: "Test"
        network: "192.16.1.0"
        prefix: 24
        state: absent
    - name: Create a test1 network
      luna_network:
        name: "Test1"
        network: "192.16.1.0"
        prefix: 24
        state: "present"
    - name: Change a test1 network
      luna_network:
        name: "Test1"
        network: "192.16.11.0"
        prefix: 24
        state: "present"
    - name: Delete a test1 network
      luna_network:
        name: "Test1"
        state: "absent"
